export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURENT_USER";

export const SET_CURRENT_LAWYER = "SET_CURRENT_LAWYER";
export const GET_CURRENT_LAWYER = "GET_CURENT_LAWYER";

export const GET_REVIEW_DETAILS = "GET_REVIEW_DETAILS";
export const ENABLE_REVIEW_LOADING = "ENABLE_REVIEW_LOADING";
export const DISABLE_REVIEW_LOADING = "DISABLE_REVIEW_LOADING";

export const SET_CURRENT_CASE = "SET_CURENT_CASE";
export const GET_CURRENT_CASE = "SET_CURENT_CASE";

export const GET_CONTACTUS_ACTION = "GET_CONTACTUS_ACTION";
export const ENABLE_CONTACTUS_ACTION_LOADING = "ENABLE_CONTACTUS_ACTION_LOADING";
export const DISABLE_CONTACTUS_ACTION_LOADING = "DISABLE_CONTACTUS_ACTION_LOADING";

export const GET_CASE_DETAILS = "GET_CASE_DETAILS";
export const ENABLE_CASE_LOADING = "ENABLE_CASE_LOADING";
export const DISABLE_CASE_LOADING = "DISABLE_CASE_LOADING";

export const GET_PAYMENT_DETAILS = "GET_PAYMENT_DETAILS";
export const ENABLE_PAYMENT_LOADING = "ENABLE_PAYMENT_LOADING";
export const DISABLE_PAYMENT_LOADING = "DISABLE_PAYMENT_LOADING";


export const GET_LAWYER_DETAILS = "GET_LAWYER_DETAILS";
export const ENABLE_LAWYER_LOADING = "ENABLE_LAWYER_LOADING";
export const DISABLE_LAWYER_LOADING = "DISABLE_LAWYER_LOADING";

export const GET_LAW_DETAILS = "GET_LAW_DETAILS";
export const ENABLE_LAW_LOADING = "ENABLE_LAW_LOADING";
export const DISABLE_LAW_LOADING = "DISABLE_LAW_LOADING";


export const GET_CLIENT_DETAILS = "GET_CLIENT_DETAILS";
export const ENABLE_CLIENT_LOADING = "ENABLE_CLIENT_LOADING";
export const DISABLE_CLIENT_LOADING = "DISABLE_CLIENT_LOADING";

export const GET_CHAT_DETAILS = "GET_CHAT_DETAILS";
export const ENABLE_CHAT_LOADING = "ENABLE_CHAT_LOADING";
export const DISABLE_CHAT_LOADING = "DISABLE_CHAT_LOADING";

export const GET_EASYPAISARESPONCE_DETAILS = "GET_REVIEW_DETAILS";
export const ENABLE_EASYPAISARESPONCE_LOADING = "ENABLE_REVIEW_LOADING";
export const DISABLE_EASYPAISARESPONCE_LOADING = "DISABLE_REVIEW_LOADING";
